### PR TITLE
Updates securedrop logo in different parts of the website

### LINKED ISSUE #692: Update Logos
## Problem
In 2019 the logos were given a polish, and subsequently need to be updated across the site. [This is the ticket](https://github.com/freedomofpress/securedrop-ux/issues/71) for the design work in the UX repo, for reference. 

## Solution
This ticket is for implementation and to manage delivery/iteration of art assets.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes https://github.com/freedomofpress/securedrop.org/issues/692#issuecomment-684061031

- Updated the logo in header section to remove a bit of space in the left. Seems aligned properly with the rest of the hexagons to my eyes (tried zooming and checking few times)

- Updated header logo PNG to use 3x size. Also, added a detect-js code in the common.js to detect JS for SVG fallback throughout the website.

- Made the footer 10% more transparent, but not sure it really shows. 

cc: @harrislapiroff @ninavizz

### CODE REVIEW

**Comment by SaptakS** [comment]
Screenshot of header logo:

image

**Comment by SaptakS** [comment]
Screenshot of footer logo:
image

**Comment by SaptakS** [comment]
Screenshot of home page logo:
image

I tried to align the lines in the hexagons surrounding the logo, and seems to my eyes that they are properly aligned now.

**Review by chigby — APPROVED** [review]
Looked over this locally and agree that the changes seem to address the issues raised. I'm going to merge this so we can get it to staging for a wider audience.

**Pull request merged**
