### PR TITLE
Fix tor detection logic in browser

### LINKED ISSUE #1034: "Detect Tor" logic is currently broken
As reported by @Thorin-Oakenpants in https://github.com/freedomofpress/securedrop/issues/6795, the logic to detect Tor Browser is currently broken - we're displaying the "You are not anonymous while using this browser!" warning message even to Tor Browser users, using latest Tor Browser. Thorin suggested an alternative detection method [here](https://github.com/freedomofpress/securedrop/issues/6795#issuecomment-1629768627); whichever method we use, we'll likely want to stay in sync between the `securedrop` and `securedrop.org` repos.

### PR DESCRIPTION
**Pull request by SaptakS**
## Description

Fixes #1034.

Changes proposed in this pull request:
Fixes detection of Tor browser logic. There are few different things that I have done in this PR that needs to be checked (though it just updates and fixes the detection logic):
- Adds `resource://` URL loading check to check for sure that it is a Tor Browser.
- Updates the Tor Browser User Agent regex
- Keeps both the previous checks and adds the resource URL check as a fallback to identify guaranteedly (for now) that it's a Tor Browser.
- I have removed the `is_likely_mobile_tor_browser` function since it was not being used in the logic. The JS code shows the same message for all mobile browsers irrespective of whether it's Tor, Chrome, Firefox or something else
- Adds a `is_like_desktop_tor_browser` function to ensure that the Tor Browser security level message is shown only in Desktop Tor browser.

## Type of change

- [x] Bug fix
- [ ] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

How should the reviewer test this PR?
Since testing of this PR involves opening the website in Tor Browsers, the reviewer will probably need ngrok or something similar. Once you have local instance running and ngrok setup, open the forwarding URL in the various browsers to check the below scenario:
- Go to admin section. Go to Settings -> Tor Alert Settings, and update the information for "Tor not detected", "Tor settings too low" and "Tor mobile alert" 
- Open the URL in a desktop non-Tor browser (e.g. firefox, chrome). The information from "Tor not detected" settings should show
- Open the URL in Tor Browser desktop. The information from "Tor settings too low" should show in `safe` and `safer` levels.
- Open the URL in mobile chrome, and mobile tor browser. Both should show the information from "Tor mobile alert".

### Post-deployment actions

In case this PR needs any admin changes or run a management command after deployment, mention it here:

### General checks

- [x] Linting and tests pass locally
- [x] The website and the changes are functional in Tor Browser
- [x] There is no conflicting migrations
- [x] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [x] The changes are accessible using keyboard and screenreader

### CODE REVIEW

**Comment by eloquence** [comment]
As discussed in web sync today, this approach makes sense to me. Just to double-check, neither Tor browser check will identify Tor Browser for Android as "Tor Browser", correct? If so, should we make the function name even more explicit, something like `is_likely_tor_browser_desktop`?

**Comment by SaptakS** [comment]
@eloquence I have made some changes to ensure it is a Tor desktop browser and updated the name for the function.

**Comment by chigby** [comment]
Is there a mobile Tor browser for ios?

**Comment by SaptakS** [comment]
@chigby there is [Onion Browser](https://onionbrowser.com/) maintained by Guardian Project, but not a Tor browser by the Tor project.

**Comment by chigby** [comment]
I guess I should ask: should I use https://onionbrowser.com/ for testing this PR?

**Review by chigby — APPROVED** [review]
I ran through the suggested suite of tests with ngrok and all of them had the expected results: non-Tor desktop got the non-Tor alert, safe/safer Tor got the Tor settings alert, and mobile tor/mobile safari got the mobile alert. 

Code looks fine as well, though I'm not focused to much on that as it has the correct results.

**Pull request merged**
