### PR TITLE
Adds styling to improve mobile tor banner

### LINKED ISSUE #701: "Pls use Tor" banner interferes with usability on mobile
The "You are not anonymous while using this browser" takes up the whole screen on mobile browsers, interfering with basic site usability. In Firefox/Tor mobile versions, it also renders incorrectly for me, with the "X" to close not visible without scrolling horizontally, making the site very difficult to use.

Moreover, the guidance is misleading on mobile: If you download the mobile version of Tor Browser, you will still get the banner (we don't recommend using mobile versions of Tor for actual SecureDrop submissions).

We should come up with more appropriate security guidance for mobile users, and consider a design that's less disruptive of other site uses.

### PR DESCRIPTION
**Pull request by SaptakS**
Fixes #701

### CODE REVIEW

**Comment by chigby** [comment]
So, I did some testing of this and the code seems fine as it is, but I want to mention that I was not able to reproduce the original issue of a horizontal scrollbar hiding the close link on the Tor warning (on securedrop.org) using mobile Firefox, desktop Firefox & Tor using various small-sized screen widths.

**Comment by SaptakS** [comment]
Interesting. I was able to reproduce it perfectly. The banner was overflowing on the right side. Not on chrome, but on mobile firefox and tor (though not on responsive mode when doing via desktop)

**Comment by chigby** [comment]
It's possible it's just the phone I used for testing (iphone 8 plus) is a slightly different size from others. I'll consider it fixed it you are seeing it fixed.

**Comment by SaptakS** [comment]
I did test in tor and firefox via ngrok and looked fixed to me.

**Comment by chigby** [comment]
Sounds good to me, in that case.

**Comment by SaptakS** [comment]
@harrislapiroff SDO remains unaffected by setuptools

**Pull request merged**
