### PR TITLE
Replaces placeimg with unsplash in createdevdata

### PR DESCRIPTION
**Pull request by SaptakS**
## Description
Changes proposed in this pull request:

We were using placeimg.com in our createdevdata who have stopped their services since June 2023. I have updated the code to use unsplash instead which is what we use in our other websites.

## Type of change

- [x] Bug fix but dev side
- [ ] New feature
- [ ] Vulnerabilities update
- [ ] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy
- [ ] Includes a database migration removing  or renaming a field

## Testing

How should the reviewer test this PR?
- Check that the createdevdata management command works correctly in an empty db.

### General checks

- [x] Linting and tests pass locally
- [x] The website and the changes are functional in Tor Browser
- [x] There is no conflicting migrations
- [x] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [x] The changes are accessible using keyboard and screenreader

### CODE REVIEW

**Review by chigby — APPROVED** [review]
Change looks good from here :+1:

**Comment by chigby** [comment]
Oh! @sssoleileraaa were you going to review this? I saw this and just processed it without really looking too hard at all the notes on it.

**Comment by sssoleileraaa** [comment]
Thanks @chigby. Glad you took a look and I was just getting started at review but lots of meetings today, so don't want to hold you up! I'll unassign myself.

**Comment by sssoleileraaa** [comment]
Oh I see. It's already merged! So nothing to do here. :)

**Comment by chigby** [comment]
Yeah, didn't mean to steal your thunder there!

**Pull request merged**
