### PR TITLE
Adds pull request template

### PR DESCRIPTION
**Pull request by SaptakS**
## Description

Fixes https://github.com/freedomofpress/fpf-www-projects/issues/343.

Changes proposed in this pull request:
I have used the deployment checklist as well as some common checks that we are expected to do along with few other points that are often included in a pull request. I have used the same template in this PR (copy-pasted) for a better idea of how things would look. All the parts are editable and people can use their own discretion if they want to  add or remove any part.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] Vulnerabilities update
- [x] Config changes
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires an admin update after deploy

## Testing

How should the reviewer test this PR?
One can check this markdown (or the one in PR) to decide if something is missing or something is wrong and needs to be changed.

### General checks

- [x] Linting and tests pass locally
- [ ] The website and the changes are functional in Tor Browser
- [ ] There is no conflicting migrations
- [ ] Any CSP related changes required has been updated (check at least both firefox & chrome)
- [ ] The changes are accessible using keyboard and screenreader

### If you made changes to directory listing:

- [ ] Verify directory filters (country/topic/language) work as expected
- [ ] Verify directory search works as expected

### If you made changes to contact form

- [ ] Verify contact form submissions works as expected
- [ ] Verify if any CSP changes required (test at least both firefox & chrome)

### If you made changes to scanner

- [ ] Verify that the directory scan result page in admin interface loads as expected
- [ ] Verify that the API at `/api/v1/directory` returns directory entries and scan results as expected

### If it's a major change

- [ ] Do the changes need to be tested in a separate staging instance?

### If you made any frontend change

If the PR involves some visual changes in the frontend, it is recommended to add a screenshot of the new visual.

### CODE REVIEW

**Comment by chigby** [comment]
I wonder if we could add a checkbox for whether the PR includes a database migration that removes or renames a field. If it does, and the code that uses the field is also updated, there is the potential for small downtime during deployment.

**Review by harrislapiroff — CHANGES_REQUESTED** [review]
I think this looks great. Only thing I might add is another optional text section for "# Post-deployment actions" (or some similar title) for any PRs that require action after deploy (update a section of the wagtail admin or run a management command or whatever).

**Comment by SaptakS** [comment]
The safety check should be fixed in https://github.com/freedomofpress/fpf-misc-resources/pull/12

**Comment by harrislapiroff** [comment]
Will override to merge for now

**Review by harrislapiroff — APPROVED** [review]

**Pull request merged**
