### PR TITLE
Update logos

### LINKED ISSUE #692: Update Logos
## Problem
In 2019 the logos were given a polish, and subsequently need to be updated across the site. [This is the ticket](https://github.com/freedomofpress/securedrop-ux/issues/71) for the design work in the UX repo, for reference. 

## Solution
This ticket is for implementation and to manage delivery/iteration of art assets.

### PR DESCRIPTION
**Pull request by chigby**
This pull request updates the site logo in the following places:

1. The transparent logo in the "hero" graphic on the home page
2. The transparent logo in the site footer
3. The header logo on pages other than the home page
4. The favicon

I left the old images in the repo, but they could be removed if we want to. I also didn't adjust the spacing at all, as the new art looks fine to my eye, though I could imagine others feeling differently. Please let me know if the sizing or spacing feels off or incorrect.

Fixes #692

### CODE REVIEW

**Comment by ninavizz** [comment]
Could someone maybe take screenshots and post 'em here for me to looksie?

**Comment by SaptakS** [comment]
All the screenshots below are taken at 2560 X 1440 screen:

Hero Image:
image


Footer logo:
image


Header logo in non-home pages:
image

@ninavizz I hope that helps.

**Comment by chigby** [comment]
It looks like one thing that's going on here is the new hero logo SVG file had some "padding" around it, whereas the old one didn't, so the new one didn't maintain the same size as the old one when slotted into the same box on the page. I assumed this was just an artistic decision, sorry everyone! I've adjusted the SVG file to remove the whitespace around the outside and the fit is much closer now:

image

Though please let me know if there are other things you notice or would like screenshots of. There are almost certainly nuances here I'm not considering :sweat_smile:

**Comment by eloquence** [comment]
This looks pretty good from my end. Having the background pattern visible through the cube in the footer is the only thing that looks a bit off to me. Will ping Nina for review when she's available.

**Pull request merged**
